#!/usr/bin/env bash

# If running from an extracted image, then export ARGV0 and APPDIR
if [ -z "${APPIMAGE}" ]; then
    EXEPATH=`realpath $0`
    export APPDIR=`dirname $EXEPATH`
    export ARGV0="$0"
fi

# Try to make sure we have a browser.
if [ -n $BROWSER ]; then
    if [ -e /usr/bin/wslview ]; then
	export BROWSER=/usr/bin/wslview
    elif [ -e /usr/bin/firefox ]; then
	     export BROWSER=/usr/bin/firefox
    fi
fi

	
# Resolve the calling command (preserving symbolic links).
export APPIMAGE_COMMAND=$(command -v -- "$ARGV0")

if [ $# == 1 ] && [ $1 == --install ]; then
    if [ -z "${APPIMAGE}" ]; then
        echo "The --install option requires a packed AppImage."
        exit 1
    fi
    if [ -z "${XDG_DATA_HOME}" ]; then
        XDG_DATA_HOME="$HOME/.local/share"
    fi
    mkdir -p "${XDG_DATA_HOME}/applications"
    mkdir -p "${XDG_DATA_HOME}/icons"
    sed -e "s|Exec=.*|Exec=${APPIMAGE}|" "${APPDIR}/sagemath.desktop" >"${XDG_DATA_HOME}/applications/sagemath.desktop"
    cp "${APPDIR}/sage_icon.svg" "${XDG_DATA_HOME}/icons"
else
    rm -f /var/tmp/sage-10.7
    ln -s "${APPDIR}/app_root" /var/tmp/sage-10.7
    export TERM=xterm-color
    "${APPDIR}/app_root/local/bin/sage" $@
fi

