#!/usr/bin/env bash

# If running from an extracted image, then export ARGV0 and APPDIR
if [ -z "${APPIMAGE}" ]; then
    EXEPATH=`realpath $0`
    export APPDIR=`dirname $EXEPATH`
    export ARGV0="$0"
fi

# Resolve the calling command (preserving symbolic links).
export APPIMAGE_COMMAND=$(command -v -- "$ARGV0")

if [ $# == 1 ] && [ $1 == --install-desktop ]; then
    if [[ -z "${APPIMAGE}" ]]; then
        echo "The --install-desktop option requires a packed AppImage."
        exit 1
    fi
    if [[ -z "${XDG_DATA_HOME}" ]]; then
        XDG_DATA_HOME="$HOME/.local/share"
    fi
    mkdir -p "${XDG_DATA_HOME}/applications"
    mkdir -p "${XDG_DATA_HOME}/icons"
    sed -e "s|Exec=.*|Exec=${APPIMAGE}|" "${APPDIR}/sagemath.desktop" >"${XDG_DATA_HOME}/applications/sagemath.desktop"
    cp "${APPDIR}/sage_icon.svg" "${XDG_DATA_HOME}/icons"
else
    # SAGE_BROWSER always overrides BROWSER if SAGE_BROWSER is defined.
    # On WSL if SAGE_BROWSER is not set we use the Windows default browser.
    
    if [[ -z "${SAGE_BROWSER}" ]]; then
	if echo `uname -r` | grep microsoft >/dev/null; then
	    BROWSER="${APPDIR}/wsl_browser"
	fi
    else 
	BROWSER="${SAGE_BROWSER}"
    fi
    rm -f /var/tmp/sage-10.8
    ln -s "${APPDIR}/app_root" /var/tmp/sage-10.8
    export TERM=xterm-color
    export BROWSER
    export PATH=/var/tmp/sage-10.8/local/bin:$PATH
    "${APPDIR}"/app_root/local/bin/sage $@
fi


